name: "Setup test server"
author: "Zxilly"
description: "Setup a test server of Notify."

runs:
  using: "composite"
  steps:
    - name: Checkout for server test
      uses: actions/checkout@v3
      if: contains(github.repository, 'server') 
      with:
        repository: 'ZNotify/server'
        path: ${{ github.run_id }}-${{ github.run_number }}

    - name: Checkout for sdk test
      uses: actions/checkout@v3
      if: contains(github.repository, 'sdk') 
      with:
        repository: 'ZNotify/server'
        ref: master
        path: ${{ github.run_id }}-${{ github.run_number }}
    
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        cache: true
        cache-dependency-path: ${{ github.run_id }}-${{ github.run_number }}/go.sum

    - name: Mkdir
      shell: bash
      run: mkdir -p ${{ github.workspace }}/${{ github.run_id }}-${{ github.run_number }}

    - name: Setup wget for windows
      shell: powershell
      if: ${{ runner.os == 'windows' }}
      run: |
        choco install wget -y

    - name: Fetch frontend asset
      shell: bash
      working-directory: ${{ github.workspace }}/${{ github.run_id }}-${{ github.run_number }}
      run: |
        wget https://github.com/ZNotify/frontend/releases/download/bundle/build.zip
        7z x build.zip
        mv build static

    - name: Build and run
      working-directory: ${{ github.workspace }}/${{ github.run_id }}-${{ github.run_number }}
      shell: bash
      run: |
        go build github.com/ZNotify/server
        ./server &
      env:
        TEST: 'true'

branding:
  icon: "airplay"
  color: "green"
