name: "Setup test server"
author: "Zxilly"
description: "Setup a test server of Notify."


runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/post.js"


branding:
  icon: "airplay"
  color: "green"