name: "Setup test server"
author: "Zxilly"
description: "Setup a test server of Notify."

runs:
  using: "composite"
  steps:
    - shell: bash
      if: contains(github.repository, "sdk") 
      run: |
        wget https://github.com/ZNotify/server/releases/download/bundle/server.zip -O server.zip
        unzip server.zip
        rm server.zip
        chmod +x server

    - uses: actions/download-artifact@v3
      if: contains(github.repository, "server") 
      with:
        name: server

    - shell: bash
      if: contains(github.repository, "server") 
      run: chmod +x server

    - shell: bash
      run: ./server &
      env:
        TEST: "true"

branding:
  icon: "airplay"
  color: "green"
