name: "Setup test server"
author: "Zxilly"
description: "Setup a test server of Notify."

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        path: artifacts

    - uses: actions/checkout@v3
      with:
        repository: "ZNotify/server"
    
    - uses: actions/setup-go@v3
      with:
        go-version: "1.19"
        cache: "true"
    
    - name: Fetch frontend asset
      shell: bash
      run: |
        wget https://github.com/ZNotify/frontend/releases/download/bundle/build.zip
        unzip build.zip
        rm build.zip
        mv build web/static

    - name: Run
      shell: bash
      run: go run notify-api &
      env:
        TEST: "true"

branding:
  icon: "airplay"
  color: "green"