name: "Setup test server"
author: "Zxilly"
description: "Setup a test server of Notify."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: "ZNotify/server"
    
    - uses: actions/setup-go@v3
      with:
        go-version: "1.19"
    

    - name: Run
      shell: bash
      run: go run notify-api
      env:
        TEST: "true"

branding:
  icon: "airplay"
  color: "green"