name: test

on: push

jobs:
  test-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download release
        run: |
          wget https://github.com/ZNotify/server/releases/download/bundle/server.zip -O server.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: server.zip

      - uses: ./

      - name: Test Port
        run: curl http://127.0.0.1:14444/alive
  
  test-compilte:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        

      - name: Test Port
        run: curl http://127.0.0.1:14444/alive
