name: test

on: push

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./

      - name: Test Port
        run: curl http://127.0.0.1:14444/alive
